kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."harbor.dev.21vianet.com".tls]
      insecure_skip_verify = true
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta1
    kind: ClusterConfiguration
    metadata:
      name: config
    networking:
      serviceSubnet: 10.0.0.0/16
    imageRepository: harbor.dev.21vianet.com/k8s_containers/
    nodeRegistration:
      kubeletExtraArgs:
        pod-infra-container-image: harbor.dev.21vianet.com/k8s_containers/pause:3.1
  - |
    apiVersion: kubeadm.k8s.io/v1beta1
    kind: InitConfiguration
    metadata:
      name: config
    networking:
      serviceSubnet: 10.0.0.0/16
    imageRepository: registry.aliyuncs.com/google_containers
nodes:
  - role: control-plane